version: 0.2

phases:
  install: 
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Checking Node.js version"
      - node -v
      - echo "Checking npm version"
      - npm -v
      - echo "Running npm install"
      - npm install || { echo 'npm install failed'; exit 1; }
  build:
    commands:
      - echo "Starting Build Phase"
      - echo "Packages & Dependencies are getting installed"
      - echo "Packages have been installed"
      - echo "Storing Build Artifact to the Location"
      - ls -la  # Add this to list files and check for files being available
artifacts:
  type: zip
  files:
    - server.js
    - package.json
    - package-lock.json
    - '**/*.js'
    - '**/*.json'
    - '**/*.html'
    - public/**/*
    - appspec.yml
    - afterinstall.sh
    - applicationstart.sh
  discard-paths: no


